apiVersion: v2
name: banking-demo
description: Banking Demo — Caddy (edge) → Kong (ClusterIP) → API Producer → NATS → Consumers
type: application
version: 1.0.0
appVersion: "10"
icon: https://raw.githubusercontent.com/cncf/artwork/main/projects/kubernetes/icon/color/kubernetes-icon-color.png
keywords:
  - banking
  - microservices
  - kong
  - nats
  - redis
maintainers:
  - name: Banking DevOps Team
    email: devops@banking-demo.local
kubeVersion: ">=1.25"
